databases:
  - name: tomuda-db
    databaseName: tomuda
    user: tomuda
    plan: free

services:
  - type: web
    name: tomuda-commerce
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py seed_tomuda
    startCommand: gunicorn tomuda.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://tomuda-commerce.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: tomuda-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11"
