from __future__ import annotations

from copy import deepcopy


PRODUCTS = [
    {
        "id": "prod-coca-cola-500",
        "barcode": "5449000000996",
        "name": "Coca Cola 500мл",
        "category": "Ундаа",
        "unit": "ширхэг",
        "boxQuantity": 24,
        "price": 3500,
        "costPrice": 2800,
        "stock": 240,
        "minStock": 48,
        "country": "АНУ",
        "image": "https://images.openfoodfacts.org/images/products/544/900/000/0996/front_en.1035.400.jpg",
    },
    {
        "id": "prod-sprite-500",
        "barcode": "5449000011527",
        "name": "Sprite 500мл",
        "category": "Ундаа",
        "unit": "ширхэг",
        "boxQuantity": 24,
        "price": 3500,
        "costPrice": 2800,
        "stock": 216,
        "minStock": 48,
        "country": "АНУ",
        "image": "https://images.openfoodfacts.org/images/products/544/900/001/1527/front_en.357.400.jpg",
    },
    {
        "id": "prod-fanta-orange-500",
        "barcode": "40822938",
        "name": "Fanta Orange 500мл",
        "category": "Ундаа",
        "unit": "ширхэг",
        "boxQuantity": 24,
        "price": 3500,
        "costPrice": 2800,
        "stock": 192,
        "minStock": 48,
        "country": "АНУ",
        "image": "https://images.openfoodfacts.org/images/products/000/004/082/2938/front_en.164.400.jpg",
    },
    {
        "id": "prod-red-bull-250",
        "barcode": "9002490100070",
        "name": "Red Bull 250мл",
        "category": "Энергийн ундаа",
        "unit": "ширхэг",
        "boxQuantity": 24,
        "price": 6500,
        "costPrice": 5300,
        "stock": 120,
        "minStock": 24,
        "country": "Австри",
        "image": "https://images.openfoodfacts.org/images/products/900/249/010/0070/front_en.245.400.jpg",
    },
    {
        "id": "prod-snickers-50",
        "barcode": "5000159461122",
        "name": "Snickers 50г",
        "category": "Амттан",
        "unit": "ширхэг",
        "boxQuantity": 48,
        "price": 4500,
        "costPrice": 3600,
        "stock": 288,
        "minStock": 48,
        "country": "Орос",
        "image": "https://images.openfoodfacts.org/images/products/500/015/946/1122/front_en.311.400.jpg",
    },
    {
        "id": "prod-mars-51",
        "barcode": "5000159459228",
        "name": "Mars 51г",
        "category": "Амттан",
        "unit": "ширхэг",
        "boxQuantity": 48,
        "price": 4500,
        "costPrice": 3600,
        "stock": 240,
        "minStock": 48,
        "country": "Орос",
        "image": "https://images.openfoodfacts.org/images/products/500/015/945/9228/front_en.289.400.jpg",
    },
    {
        "id": "prod-prince-chocolate",
        "barcode": "7622210449283",
        "name": "Prince Chocolat 300г",
        "category": "Жигнэмэг",
        "unit": "ширхэг",
        "boxQuantity": 16,
        "price": 6900,
        "costPrice": 5400,
        "stock": 96,
        "minStock": 24,
        "country": "Испани",
        "image": "https://images.openfoodfacts.org/images/products/762/221/044/9283/front_en.605.400.jpg",
    },
    {
        "id": "prod-nutella-350",
        "barcode": "3017620422003",
        "name": "Nutella 350г",
        "category": "Хүнс",
        "unit": "ширхэг",
        "boxQuantity": 12,
        "price": 15500,
        "costPrice": 12800,
        "stock": 60,
        "minStock": 12,
        "country": "Итали",
        "image": "https://images.openfoodfacts.org/images/products/301/762/042/2003/front_en.820.400.jpg",
    },
    {
        "id": "prod-pringles-original-165",
        "barcode": "5053990156009",
        "name": "Pringles Original 165г",
        "category": "Чипс",
        "unit": "ширхэг",
        "boxQuantity": 19,
        "price": 9800,
        "costPrice": 7600,
        "stock": 76,
        "minStock": 19,
        "country": "Польш",
        "image": "https://images.openfoodfacts.org/images/products/505/399/015/6009/front_fr.230.400.jpg",
    },
    {
        "id": "prod-pringles-cheese-165",
        "barcode": "5053990138715",
        "name": "Pringles Cheese 165г",
        "category": "Чипс",
        "unit": "ширхэг",
        "boxQuantity": 19,
        "price": 9800,
        "costPrice": 7600,
        "stock": 76,
        "minStock": 19,
        "country": "Польш",
        "image": "https://images.openfoodfacts.org/images/products/505/399/013/8715/front_fr.3.400.jpg",
    },
]

CUSTOMERS = [
    {
        "id": "cust-green-mart",
        "name": "Green mart",
        "registrationNumber": "6115756",
        "companyName": "Дэвжих цэцэг",
        "phone1": "88103448",
        "phone2": "",
        "province": "Улаанбаатар",
        "district": "Баянзүрх",
        "khoroo": "26-р хороо",
        "address": "Олимп хороолол, төв зам дагуу",
        "latitude": "47.916935",
        "longitude": "106.951798",
        "locationText": "Олимп хорооллын урд тал",
    },
    {
        "id": "cust-tanhil-market",
        "name": "Танхил маркет",
        "registrationNumber": "7125409",
        "companyName": "Төгс энх танхил",
        "phone1": "80805060",
        "phone2": "",
        "province": "Улаанбаатар",
        "district": "Сүхбаатар",
        "khoroo": "3-р хороо",
        "address": "Сансар гарден хотхон 39-6-1",
        "latitude": "47.925309",
        "longitude": "106.930147",
        "locationText": "Чингис зочид буудлын баруун урд",
    },
    {
        "id": "cust-s-market",
        "name": "S market",
        "registrationNumber": "6686702",
        "companyName": "Айбынды",
        "phone1": "89089508",
        "phone2": "",
        "province": "Улаанбаатар",
        "district": "Баянзүрх",
        "khoroo": "1-р хороо",
        "address": "17А байр, Сансрын тунелийн зүүн хойно",
        "latitude": "47.922824",
        "longitude": "106.936117",
        "locationText": "Сансрын үйлчилгээний төвийн ойролцоо",
    },
]

EMPLOYEES = [
    {
        "id": "emp-hasan",
        "name": "Хасан",
        "email": "ht@tomuda.mn",
        "phone": "88001111",
        "password": "hasan",
        "role": "sales",
        "totalSales": 0,
        "commissionRate": 2,
    },
    {
        "id": "emp-galsan",
        "name": "Галсанцэрэн",
        "email": "ht.galsan@tomuda.mn",
        "phone": "99191848",
        "password": "galsan",
        "role": "sales",
        "totalSales": 0,
        "commissionRate": 2,
    },
    {
        "id": "emp-munkh",
        "name": "Мөнх-Эрдэнэ",
        "email": "ht.munkh@tomuda.mn",
        "phone": "88001234",
        "password": "munkh",
        "role": "sales",
        "totalSales": 0,
        "commissionRate": 2,
    },
    {
        "id": "emp-dulam",
        "name": "Дуламсүрэн",
        "email": "aguulah@tomuda.mn",
        "phone": "99076727",
        "password": "dulam",
        "role": "warehouse",
        "totalSales": 0,
        "commissionRate": 0,
    },
    {
        "id": "admin",
        "name": "Админ",
        "email": "admin@tomuda.mn",
        "phone": "99000000",
        "password": "admin",
        "role": "admin",
        "totalSales": 0,
        "commissionRate": 0,
    },
]


def default_state() -> dict:
    return deepcopy(
        {
            "customers": CUSTOMERS,
            "products": PRODUCTS,
            "employees": EMPLOYEES,
            "orders": [],
            "extraCategories": [],
            "inventoryLogs": [],
            "countQty": {},
            "countDone": False,
            "workerCustomer": "cust-green-mart",
            "orderEmployee": "emp-hasan",
            "promotionRules": {"quantity": [], "price": []},
            "deliveryDate": "",
            "paymentTerm": "cash",
            "selectedWorkers": [],
            "selectedWarehouseOrderId": "",
            "deliveryName": "Дуламсүрэн",
            "deliveryPhone": "99076727",
            "workerQty": {},
            "settings": {
                "stockAlertEnabled": True,
                "stockAlertMin": 10,
            },
        }
    )
