# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(db_index=True, max_length=160, unique=True),
                ),
                ("image", models.BinaryField()),
                (
                    "content_type",
                    models.CharField(default="image/jpeg", max_length=64),
                ),
                ("ext", models.CharField(default="jpg", max_length=8)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
