# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_productimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=16)),
                ("entity_id", models.CharField(db_index=True, max_length=160)),
                ("image", models.BinaryField()),
                (
                    "content_type",
                    models.CharField(default="image/jpeg", max_length=64),
                ),
                ("ext", models.CharField(default="jpg", max_length=8)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "entity_id"),
                        name="dashboard_profileimage_kind_entity_id_uniq",
                    )
                ],
            },
        ),
    ]
